"""add user_id to generations

Revision ID: 0ca935824641
Revises: ae596001332f
Create Date: 2026-06-01 04:46:06.417464

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ca935824641'
down_revision: str | Sequence[str] | None = 'ae596001332f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('user_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_generations_user_id'), 'generations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generations_user_id'), table_name='generations')
    op.drop_column('generations', 'user_id')
    # ### end Alembic commands ###
