"""initial schema

Revision ID: 0e0b2580c881
Revises:
Create Date: 2026-05-29 14:14:26.756849

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e0b2580c881"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_usage_model"), "api_usage", ["model"], unique=False)
    op.create_index(op.f("ix_api_usage_request_id"), "api_usage", ["request_id"], unique=False)
    op.create_table(
        "generations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("image_hash", sa.String(length=64), nullable=False),
        sa.Column("preset_id", sa.String(length=80), nullable=False),
        sa.Column("instruction_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("original_path", sa.String(length=500), nullable=True),
        sa.Column("output_path", sa.String(length=500), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_generations_cache_lookup",
        "generations",
        ["image_hash", "preset_id", "instruction_hash", "model", "prompt_version", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_generations_image_hash"), "generations", ["image_hash"], unique=False)
    op.create_index(
        op.f("ix_generations_instruction_hash"),
        "generations",
        ["instruction_hash"],
        unique=False,
    )
    op.create_index(op.f("ix_generations_model"), "generations", ["model"], unique=False)
    op.create_index(op.f("ix_generations_preset_id"), "generations", ["preset_id"], unique=False)
    op.create_index(
        op.f("ix_generations_prompt_version"),
        "generations",
        ["prompt_version"],
        unique=False,
    )
    op.create_index(op.f("ix_generations_request_id"), "generations", ["request_id"], unique=True)
    op.create_index(op.f("ix_generations_status"), "generations", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generations_status"), table_name="generations")
    op.drop_index(op.f("ix_generations_request_id"), table_name="generations")
    op.drop_index(op.f("ix_generations_prompt_version"), table_name="generations")
    op.drop_index(op.f("ix_generations_preset_id"), table_name="generations")
    op.drop_index(op.f("ix_generations_model"), table_name="generations")
    op.drop_index(op.f("ix_generations_instruction_hash"), table_name="generations")
    op.drop_index(op.f("ix_generations_image_hash"), table_name="generations")
    op.drop_index("ix_generations_cache_lookup", table_name="generations")
    op.drop_table("generations")
    op.drop_index(op.f("ix_api_usage_request_id"), table_name="api_usage")
    op.drop_index(op.f("ix_api_usage_model"), table_name="api_usage")
    op.drop_table("api_usage")
    # ### end Alembic commands ###
